### ISSUE TITLE
Add India in list of country badges

### ISSUE THREAD

**Issue by kushalpandya** [stevenmhunt/badgerly#4]
I'd love to see my country India in one of those badges, if you plan to add it, I'm more than happy to send PR for the same! :smiley:

**Comment by stevenmhunt** [comment]
Yes, I definitely want to keep adding more countries and other features that people using the code want to add. How could I forget 1/6th of the Earth's total population :smiley: ? I won't have time to work on it until the weekend, but if you submit a PR in the mean time I would be happy to merge it in. Thanks!

**Comment by kushalpandya** [comment]
I'm working on to add Indian flag, but as you've mentioned in README that SCSS transpilation is handled via Webstorm, is there any alternate way I can push changes to CSS file (apart from manually editing it)? as I don't own WebStorm IDE.

**Comment by stevenmhunt** [comment]
I have fixed this in #5 and there is now a gulpfile to run. The instructions are in the readme. Happy coding!

**Comment by stevenmhunt** [comment]
This has been published to Bower starting in v0.2.0. Thanks for your help!
