### ISSUE TITLE
.gitignore is missing node_modules

### ISSUE THREAD

**Issue by kushalpandya** [stevenmhunt/badgerly#7]
Looks like `.gitignore` doesn't have `node_modules` folder included, leading to all the modules shown in diff after running `npm install`.

**Comment by stevenmhunt** [comment]
Oops, sorry about that :smile: I'll fix it in the master in a few minutes, then you can pull the changes into your fork.

**Comment by kushalpandya** [comment]
I'm making a pull request for the same as I'm writing this.
