### ISSUE TITLE
Feature Request - Use npm script to run SASS build

### ISSUE THREAD

**Issue by kushalpandya** [stevenmhunt/badgerly#9]
Currently we do `npm install` and then need to also install `gulp` as global command using `npm install -g gulp` to be able to run `gulp sass` and build CSS files. However, it would be nice we add it as one of the npm script target (in `package.json`) such that we can simply run `npm run build`, (as npm scripts have access to all the module commands in PATH).

I'll submit another PR for the same. This will reduce an extra installation step and speed up the workflow. :smiley:

**Comment by stevenmhunt** [comment]
Sounds great! Thanks for the contributions :wine_glass: cheers!
